name: Build AppImage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-x86_64:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        # Install all dependencies in one consolidated step
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          curl \
          wget \
          file \
          ninja-build \
          clang \
          lld \
          pkg-config \
          libc6-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libpng-dev \
          libuv1-dev \
          libzip-dev \
          libglib2.0-dev \
          qtbase5-dev \
          qtbase5-dev-tools \
          qttools5-dev \
          qttools5-dev-tools \
          qt5-qmake \
          libqt5svg5-dev \
          qtwebengine5-dev \
          qtwebengine5-dev-tools \
          libqt5webenginecore5 \
          libqt5webenginewidgets5 \
          qtdeclarative5-dev \
          qml-module-qtquick-controls2 \
          qml-module-qtquick-layouts \
          qml-module-qtquick-window2 \
          qml-module-qtquick-dialogs \
          qml-module-qtwebengine \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          libx11-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxi-dev \
          libxrandr-dev \
          libxtst6 \
          libxss1 \
          libasound2-dev \
          libpulse-dev \
          libudev-dev \
          libevdev-dev \
          libnss3-dev \
          libprotobuf-dev \
          protobuf-compiler

    - name: Setup environment
      run: |
        echo "MAKE_JOBS=$(nproc)" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV

    - name: Test dependencies
      run: |
        ./test-dependencies.sh

    - name: Build AppImage (Qt5)
      run: |
        ./build_appimage.sh -t x86_64 -m -n -j ${MAKE_JOBS} -q quirks-modern.sh

    - name: Upload AppImage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: appimage-x86_64-qt5
        path: output/*.AppImage
        retention-days: 7

    - name: Upload zsync files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zsync-x86_64-qt5
        path: output/*.zsync
        retention-days: 7

