name: Build AppImage - Qt6 x86_64 Only

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-x86_64:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        # Install all dependencies in one consolidated step
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          curl \
          wget \
          file \
          ninja-build \
          clang \
          lld \
          pkg-config \
          libc6-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libpng-dev \
          libuv1-dev \
          libzip-dev \
          libglib2.0-dev \
          qt6-base-dev \
          qt6-base-dev-tools \
          qt6-tools-dev \
          qt6-tools-dev-tools \
          qmake6 \
          libqt6svg6-dev \
          qt6-webengine-dev \
          qt6-webengine-dev-tools \
          libqt6webenginecore6 \
          libqt6webenginewidgets6 \
          qt6-declarative-dev \
          qml6-module-qtquick-controls \
          qml6-module-qtquick-layouts \
          qml6-module-qtquick-window \
          qml6-module-qtquick-dialogs \
          qml6-module-qtwebengine \
          qt6-wayland \
          qt6-wayland-dev \
          libqt6opengl6-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libgles2-mesa-dev \
          libx11-dev \
          libxext-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxi-dev \
          libxrandr-dev \
          libxtst6 \
          libxss1 \
          libasound2-dev \
          libpulse-dev \
          libudev-dev \
          libevdev-dev \
          libnss3-dev \
          libprotobuf-dev \
          protobuf-compiler

    - name: Setup environment
      run: |
        echo "MAKE_JOBS=$(nproc)" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "QT_VERSION=6" >> $GITHUB_ENV
        echo "CMAKE_QT_VERSION=Qt6" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig" >> $GITHUB_ENV

    - name: Test dependencies
      run: |
        ./test-dependencies.sh

    - name: Build AppImage (Qt6 x86_64)
      run: |
        ./build_appimage.sh -t x86_64 -n -j ${MAKE_JOBS} -q quirks-qt6.sh

    - name: Validate AppImage Quality
      run: |
        ./validate-appimage.sh

    - name: Analyze Build Logs
      run: |
        ./analyze-build-logs.sh

    - name: Upload AppImage artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: appimage-x86_64-qt6
        path: output/*.AppImage
        retention-days: 7

    - name: Upload zsync files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zsync-x86_64-qt6
        path: output/*.zsync
        retention-days: 7

    - name: Upload validation reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validation-reports
        path: validation/*.md
        retention-days: 30

